import { AlertQueueInterface } from './AlertQueue.interface';
import { BundleInterface } from './Bundle.interface';
import { EduContentMetadataInterface } from './EduContentMetadata.interface';
import { EduContentNoteInterface } from './EduContentNote.interface';
import { FavoriteInterface } from './Favorite.interface';
import { GroupInterface } from './Group.interface';
import { HistoryInterface } from './History.interface';
import { LearningAreaInterface } from './LearningArea.interface';
import { LicenseInterface } from './License.interface';
import { MessageInterface } from './Message.interface';
import { MessagePersonInterface } from './MessagePerson.interface';
import { MethodInterface } from './Method.interface';
import { PassportUserCredentialInterface } from './PassportUserCredential.interface';
import { PassportUserIdentityInterface } from './PassportUserIdentity.interface';
import { PersonPreferenceInterface } from './PersonPreference.interface';
import { PersonToggleFeatureInterface } from './PersonToggleFeature.interface';
import { PurchaseInterface } from './Purchase.interface';
import { PurchaseAddressInterface } from './PurchaseAddress.interface';
import { ResultInterface } from './Result.interface';
import { RoleInterface } from './Role.interface';
import { RoleMappingInterface } from './RoleMapping.interface';
import { SchoolAddressInterface } from './SchoolAddress.interface';
import { StudentContentStatusInterface } from './StudentContentStatus.interface';
import { TaskInterface } from './Task.interface';
import { TaskInstanceInterface } from './TaskInstance.interface';
import { TeacherInfoInterface } from './TeacherInfo.interface';
import { TeacherStudentInterface } from './TeacherStudent.interface';
import { UnlockedBoekeGroupInterface } from './UnlockedBoekeGroup.interface';
import { UnlockedBoekeStudentInterface } from './UnlockedBoekeStudent.interface';
import { UnlockedContentInterface } from './UnlockedContent.interface';
import { UnlockedContentGroupInterface } from './UnlockedContentGroup.interface';
import { UnlockedContentStudentInterface } from './UnlockedContentStudent.interface';
import { UserContentInterface } from './UserContent.interface';

export interface PersonInterface {
  name?: string;
  firstName?: string;
  created?: Date;
  gender?: string;
  type?: string;
  avatar?: any;
  email: string;
  currentSchoolYear?: number;
  terms?: boolean;
  realm?: string;
  username?: string;
  emailVerified?: boolean;
  id?: number;
  displayName?: string;
  password?: string;
  accessTokens?: any[];
  roles?: RoleInterface[];
  rolemappings?: RoleMappingInterface[];
  credentials?: PassportUserCredentialInterface[];
  identities?: PassportUserIdentityInterface[];
  teachers?: PersonInterface[];
  students?: PersonInterface[];
  teacherStudentByStudent?: TeacherStudentInterface[];
  teacherStudents?: TeacherStudentInterface[];
  schoolAddresses?: SchoolAddressInterface[];
  teacherInfo?: TeacherInfoInterface;
  messages?: MessageInterface[];
  ownsGroups?: GroupInterface[];
  personPreferences?: PersonPreferenceInterface[];
  methods?: MethodInterface[];
  licenses?: LicenseInterface[];
  teacherUnlockedContents?: UnlockedContentInterface[];
  teacherUnlockedBoekeStudents?: UnlockedBoekeStudentInterface[];
  teacherUnlockedBoekeGroups?: UnlockedBoekeGroupInterface[];
  studentUnlockedContents?: UnlockedContentInterface[];
  teacherUnlockedContentStudents?: UnlockedContentStudentInterface[];
  teacherUnlockedContentGroups?: UnlockedContentGroupInterface[];
  teacherTasks?: TaskInterface[];
  studentTasks?: TaskInterface[];
  studentResults?: ResultInterface[];
  results?: ResultInterface[];
  studentContentStatuses?: StudentContentStatusInterface[];
  eduContentMetadata?: EduContentMetadataInterface[];
  eduContentNotes?: EduContentNoteInterface[];
  bundles?: BundleInterface[];
  favorites?: FavoriteInterface[];
  favoriteAreas?: LearningAreaInterface[];
  history?: HistoryInterface[];
  purchaseAddresses?: PurchaseAddressInterface[];
  purchases?: PurchaseInterface[];
  groups?: GroupInterface[];
  incomingMessages?: MessageInterface[];
  messagePersons?: MessagePersonInterface[];
  taskInstances?: TaskInstanceInterface[];
  ownsAlerts?: AlertQueueInterface[];
  alertQueues?: AlertQueueInterface[];
  userContents?: UserContentInterface[];
  personToggleFeatures?: PersonToggleFeatureInterface[];
}
