import { DiaboloPhaseInterface } from './DiaboloPhase.interface';
import { EditorStatusInterface } from './EditorStatus.interface';
import { EduContentInterface } from './EduContent.interface';
import { EduContentProductTypeInterface } from './EduContentProductType.interface';
import { EduContentSourceInterface } from './EduContentSource.interface';
import { EduContentTagInterface } from './EduContentTag.interface';
import { EduContentTOCInterface } from './EduContentTOC.interface';
import { EduNetInterface } from './EduNet.interface';
import { GradeInterface } from './Grade.interface';
import { LearningAreaInterface } from './LearningArea.interface';
import { LearningDomainInterface } from './LearningDomain.interface';
import { LearningPlanInterface } from './LearningPlan.interface';
import { MethodInterface } from './Method.interface';
import { PersonInterface } from './Person.interface';
import { PublisherInterface } from './Publisher.interface';
import { SchoolTypeInterface } from './SchoolType.interface';
import { TechnicalRequirementInterface } from './TechnicalRequirement.interface';
import { YearInterface } from './Year.interface';

export interface EduContentMetadataInterface {
  version: number;
  metaVersion: string;
  language: string;
  title?: string;
  description?: string;
  created: Date;
  published?: Date;
  quotable?: boolean;
  taskAllowed?: boolean;
  standalone?: boolean;
  teacherCanUnlock?: boolean;
  fileName?: string;
  file?: string;
  checksum?: string;
  link?: string;
  commitMessage?: string;
  previewId?: string;
  thumb?: string;
  thumbSmall?: string;
  showCommitMessage?: boolean;
  locked?: boolean;
  sourceRef?: string;
  id?: number;
  publisherId?: number;
  eduContentId?: number;
  editorId?: number;
  learningAreaId?: number;
  diaboloPhaseId?: number;
  eduContentProductTypeId?: number;
  editorStatusId?: number;
  eduContentSourceId?: number;
  publisher?: PublisherInterface;
  relatedContents?: EduContentInterface[];
  eduContent?: EduContentInterface;
  methods?: MethodInterface[];
  editor?: PersonInterface;
  schoolTypes?: SchoolTypeInterface[];
  technicalRequirements?: TechnicalRequirementInterface[];
  learningArea?: LearningAreaInterface;
  diaboloPhase?: DiaboloPhaseInterface;
  learningDomains?: LearningDomainInterface[];
  eduContentProductType?: EduContentProductTypeInterface;
  learningPlans?: LearningPlanInterface[];
  editorStatus?: EditorStatusInterface;
  eduNets?: EduNetInterface[];
  tags?: EduContentTagInterface[];
  years?: YearInterface[];
  grades?: GradeInterface[];
  eduContentTOC?: EduContentTOCInterface[];
  eduContentSource?: EduContentSourceInterface;
  fileExt?: string;
  fileLabel?: string;
  methodIds?: number[];
  streamable?: boolean;
  eduContentBookId?: number;
}
