export const icons = {
  book: 'assets/icons/book.svg',
  warning: 'assets/icons/material/baseline-warning-24px.svg',
  menu: 'assets/icons/material/menu.svg',
  favorite: 'assets/icons/material/favorite.svg',
  home: 'assets/icons/material/home.svg',
  magnifier: 'assets/icons/magnifier.svg',
  download: 'assets/icons/material/download.svg',
  'exercise:open': 'assets/icons/exercise-open.svg',
  'exercise:finished': 'assets/icons/exercise-finished.svg',
  methods: 'assets/icons/methods.svg', //Temp icon
  tasks: 'assets/icons/tasks.svg', //Temp icon
  results: 'assets/icons/results.svg', //Temp icon
  differentiate: 'assets/icons/differentiate.svg', //Temp icon
  'select-all': 'assets/icons/done_all.svg',
  'import-export': 'assets/icons/material/import-export.svg',
  'quicklink:favorites': 'assets/icons/favorites3.svg',
  'quicklink:history': 'assets/icons/clock2.svg',
  profile: 'assets/icons/profile2.svg',
  avatar: 'assets/icons/avatar.svg',
  notifications: 'assets/icons/alert2.svg',
  settings: 'assets/icons/settings.svg',
  account: 'assets/icons/account-circle.svg',
  cancel: 'assets/icons/cancel.svg',
  delete: 'assets/icons/material/delete.svg',
  edit: 'assets/icons/material/edit.svg',
  filter: 'assets/icons/filter.svg',
  context_menu: 'assets/icons/material/more_vert.svg',
  favorites: 'assets/icons/assets/icons/favorites3.svg',
  check: 'assets/icons/check.svg',
  close: 'assets/icons/close.svg',
  history: 'assets/icons/history.svg',
  boardbook: 'assets/icons/boardbook.svg',
  method: 'assets/icons/lesmateriaal.svg',
  'reset-filters': 'assets/icons/material/reset.svg',
  //TODO: These are TEMPORARY SVGs for Diabolo that I made from the PNGs
  //get the OFFICIAL files from Antoon later
  'diabolo-intro': 'assets/icons/diabolo/intro.svg',
  'diabolo-midden': 'assets/icons/diabolo/midden.svg',
  'diabolo-outro': 'assets/icons/diabolo/outro.svg',
  'arrow-back': 'assets/icons/material/arrow-back.svg',
  'breadcrumb-separator': 'assets/icons/material/chevron-right.svg',
  'collapsible-sheet-back': 'assets/icons/material/arrow-back.svg',
  file: 'assets/icons/general-file.svg',

  // search: sort modes
  'sort-numeric-down': 'assets/icons/sort-numeric-down.svg',
  'sort-alpha-down': 'assets/icons/sort-alpha-down.svg',
  'calendar-plus': 'assets/icons/calendar-plus.svg',
  'educontent-product-type:algemeen bestand': 'assets/icons/general-file.svg',
  'educontent-product-type:doelen': 'assets/icons/learning-goals.svg',
  'educontent-product-type:handleiding': 'assets/icons/general-file.svg',
  'educontent-product-type:evaluatie': 'assets/icons/general-file.svg',
  'educontent-product-type:differentiatie': 'assets/icons/general-file.svg',
  'educontent-product-type:kopieerblad': 'assets/icons/general-file.svg',
  'educontent-product-type:bijlage': 'assets/icons/general-file.svg',
  'educontent-product-type:audio': 'assets/icons/general-file.svg',
  'educontent-product-type:video': 'assets/icons/general-file.svg',
  'educontent-product-type:presentatie': 'assets/icons/general-file.svg',
  'educontent-product-type:applicatie': 'assets/icons/general-file.svg',
  'educontent-product-type:correctiesleutel': 'assets/icons/general-file.svg'
};
