export const icons = {
  book: 'assets/icons/book.svg',
  bookshelf: 'assets/icons/material/bookshelf.svg',
  warning: 'assets/icons/material/baseline-warning-24px.svg',
  menu: 'assets/icons/material/menu.svg',
  favorite: 'assets/icons/material/favorite.svg',
  home: 'assets/icons/material/home.svg',
  magnifier: 'assets/icons/magnifier.svg',
  download: 'assets/icons/material/download.svg',
  exercise: 'assets/icons/gamepad.svg',
  'exercise:open': 'assets/icons/exercise-open.svg',
  'exercise:finished': 'assets/icons/exercise-finished.svg',
  methods: 'assets/icons/methods.svg', //Temp icon
  task: 'assets/icons/tasks/assignment.svg',
  tasks: 'assets/icons/tasks/assignment.svg',
  results: 'assets/icons/results.svg', //Temp icon
  differentiate: 'assets/icons/differentiate.svg', //Temp icon
  'select-all': 'assets/icons/done_all.svg',
  'import-export': 'assets/icons/material/import-export.svg',
  'quicklink:favorites': 'assets/icons/favorite.svg',
  'quicklink:history': 'assets/icons/history.svg',
  profile: 'assets/icons/profile.svg',
  avatar: 'assets/icons/avatar.svg',
  notifications: 'assets/icons/alerts.svg',
  settings: 'assets/icons/settings.svg',
  account: 'assets/icons/account-circle.svg',
  cancel: 'assets/icons/material/cancel.svg',
  delete: 'assets/icons/material/delete.svg',
  add: 'assets/icons/material/add.svg',
  edit: 'assets/icons/material/edit.svg',
  filter: 'assets/icons/filter.svg',
  context_menu: 'assets/icons/material/more_vert.svg',
  favorites: 'assets/icons/favorite.svg',
  'favorites-filled': 'assets/icons/material/favorite-filled.svg',
  check: 'assets/icons/check.svg',
  close: 'assets/icons/close.svg',
  history: 'assets/icons/history.svg',
  boardbook: 'assets/icons/boardbook.svg',
  'reset-filters': 'assets/icons/material/filter-remove.svg',
  'general-file': 'assets/icons/general-file.svg',
  method: 'assets/icons/methods.svg',
  'drag-handle': 'assets/icons/drag-handle.svg',
  //TODO: These are TEMPORARY SVGs for Diabolo that I made from the PNGs
  //get the OFFICIAL files from Antoon later
  'diabolo-intro': 'assets/icons/diabolo/intro.svg',
  'diabolo-midden': 'assets/icons/diabolo/midden.svg',
  'diabolo-outro': 'assets/icons/diabolo/outro.svg',
  'arrow-back': 'assets/icons/material/arrow-back.svg',
  'breadcrumb-separator': 'assets/icons/material/chevron-right.svg',
  'collapsible-sheet-back': 'assets/icons/material/arrow-back.svg',
  lock: 'assets/icons/material/lock.svg',
  file: 'assets/icons/general-file.svg',
  star: 'assets/icons/star.svg',
  'star-outline': 'assets/icons/star-border.svg',
  color: 'assets/icons/color_lens.svg',
  toggle: 'assets/icons/toggle.svg',
  flip: 'assets/icons/material/flip_camera.svg',
  archive: 'assets/icons/archive.svg',
  'task:archived': 'assets/icons/archive.svg',
  'task:active': 'assets/icons/tasks/assignment_started.svg',
  'task:pending': 'assets/icons/tasks/assignment.svg',
  'task:finished': 'assets/icons/tasks/assignment_done.svg',
  'task:paper': 'assets/icons/tasks/assignment_paper.svg',
  photolibrary: 'assets/icons/photo_library.svg',
  print: 'assets/icons/printer.svg',
  preview: 'assets/icons/material/monitor_eye.svg',
  'edu-content:required': 'assets/icons/star.svg', //TODO placeholder
  'edu-content:optional': 'assets/icons/star-border.svg', //TODO placeholder
  'edu-content:level-basic': 'assets/icons/play_arrow.svg', //TODO placeholder, name needs work
  'edu-content:level-advanced': 'assets/icons/fast_forward.svg', //TODO placeholder, name needs work
  plus: 'assets/icons/add.svg',
  'rating-star': 'assets/icons/rating-star.svg',
  hourglass: 'assets/icons/material/hourglass_empty.svg',

  // search: sort modes
  'sort-numeric-down': 'assets/icons/sort-numeric-down.svg',
  'sort-alpha-down': 'assets/icons/sort-alpha-down.svg',
  'calendar-plus': 'assets/icons/calendar-plus.svg',
  'educontent-product-type:algemeen bestand': 'assets/icons/general-file.svg',
  'educontent-product-type:doelen': 'assets/icons/learning-goals.svg',
  'educontent-product-type:handleiding': 'assets/icons/general-file.svg',
  'educontent-product-type:evaluatie': 'assets/icons/general-file.svg',
  'educontent-product-type:differentiatie': 'assets/icons/general-file.svg',
  'educontent-product-type:kopieerblad': 'assets/icons/general-file.svg',
  'educontent-product-type:bijlage': 'assets/icons/general-file.svg',
  'educontent-product-type:audio': 'assets/icons/general-file.svg',
  'educontent-product-type:video': 'assets/icons/general-file.svg',
  'educontent-product-type:presentatie': 'assets/icons/general-file.svg',
  'educontent-product-type:applicatie': 'assets/icons/general-file.svg',
  'educontent-product-type:correctiesleutel': 'assets/icons/general-file.svg',

  //empty-states
  'empty-state-all-done': 'assets/empty-states/all-done.svg',
  'empty-state-no-educontent': 'assets/empty-states/no-educontent.svg',
  'empty-state-no-users': 'assets/empty-states/no-users.svg',
  'empty-state-whiteboard-empty': 'assets/empty-states/whiteboard-empty.svg',
  'empty-state-whiteboard-drop': 'assets/empty-states/whiteboard-drop.svg',

  // whiteboard icons
  'delete-forever': 'assets/icons/whiteboard/image-delete.svg',
  'add-photo-alternate': 'assets/icons/whiteboard/image-edit.svg',
  multiselect: 'assets/icons/multiselect.svg',
  'multiselect-selected': 'assets/icons/multiselect-selected.svg',
  'open-in-new': 'assets/icons/material/open_in_new.svg',
  remove: 'assets/icons/material/remove.svg',
  'arrow-down': 'assets/icons/material/arrow_down.svg'
};
